server:
  port: 8042
spring:
  application:
    name: servicio-coches
eureka:
  instance:
    instance-id: a13e11
    hostname: a13e11
  client:
    serviceUrl:
      defaultZone: http://10.1.3.100:8761/eureka